device: "cuda:0"
model : "vgg"
save_folder : "./weight/"
lr : 0.001
epochs : 10
batchsize : 32
input_channel: 6
type : "img"

csv_dir: "./data/result.csv"
img_type: ["aero", "ref", "ele", "shade"]
#img_type: ["aero"]
split_dataset: True
